--- # --------------------------------------------
# --------------------------------------------
# SERVER CONFIGURATION
server:
  port: 8080
  context-path: /

# --------------------------------------------
# SPRING SECURITY CONFIGURATION
# --------------------------------------------
security:
  ignored: /swagger-ui.html, /webjars/**, /swagger-resources/**, /v2/api-docs/**, /configuration/ui/**, /configuration/security/**, /health
  basic:
    enabled: true
  filter-order: 10
  user:
    name: admin
    password: s3cr3t

management:
  server:
    servlet:
      context-path: /admin
  security:
    enabled: false

# --------------------------------------------
# LOG CONFIGURATION
# --------------------------------------------
logging:
  file: ${spring.application.name}.log
  path: /var/log
  level:
    zipkin: "DEBUG"

# --------------------------------------------
# SPRING APP CONFIGURATION
# --------------------------------------------
spring:
  jmx:
    default-domain: cloud.config.server
  aop:
    proxy-target-class: false
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # --------------------------------------------
  # SPRING CACHE
  # --------------------------------------------
  cache:
    type: simple

  # --------------------------------------------
  # SPRING DB CONFIGURATION
  # --------------------------------------------
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://${MYSQL_URI}:3306/zipkin?autoReconnect=true
    username: user
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    continue-on-error: true

  # --------------------------------------------
  # SPRING MQ CONFIGURATION
  # --------------------------------------------
  rabbitmq:
    host: ${RABBIT_URI:172.21.1.251}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

  # --------------------------------------------
  # SLEUTH CONFIGURATION
  # --------------------------------------------
  sleuth:
    enabled: true
    sampler:
      percentage: 0.0
    rxjava:
      schedulers:
        hook:
          enabled: false

# --------------------------------------------
# RIBBON CONFIGURATION
# --------------------------------------------
ribbon:
  eureka:
    enabled: true

# --------------------------------------------
# ZIPKIN CONFIGURATION
# --------------------------------------------
zipkin:
  self-tracing:
    enabled: true
  storage:
    type: mem
  query:
    allowed-origins: "*"

# --------------------------------------------
# CUSTOM CONFIGURATIONS
# --------------------------------------------
vac:
  logger:
    enabled: true
    logger-ui:
      enabled: true
      url: http://loggerui.cashlight.io:80
  common:
    swagger: true
